name: mareli_school_app
description: Classic professional Android app for the MARELI school management system.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_ma.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_ma.png"
